### ISSUE TITLE
Properly sign for distribution

### ISSUE THREAD

**Issue by owenpshaw** [oregondesignservices/MorphicLiteClientMac#11]
- [ ] codesign so we can use features like Keychain
- [ ] Get whatever is needed from Apple to distribute outside of the Mac app store

**Comment by jvilhuber** [comment]
Some links I found:
https://damienaicheh.github.io/ios/azure/devops/2019/12/05/build-sign-your-ios-application-using-azure-devops-en.html
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?preferredLanguage=occ#3087734

**Comment by jvilhuber** [comment]
The first issue I see is that you appear to have to upload the file to notirization. It's not local.

**Comment by jvilhuber** [comment]
https://blog.zeplin.io/dev-journal-automate-notarizing-macos-apps-94b0b144ba9d
