### ISSUE TITLE
MAC Client - Build an installer

### ISSUE THREAD

**Issue by nachochris** [oregondesignservices/MorphicLiteClientMac#8]
Need build code to create the client in a signed installable, and then pushed to the download site (like windows).  Clearly we will need to have signatures for dev and for production.

**Comment by owenpshaw** [comment]
Signing should already be taken care of with the Raising the Floor Apple Developer membership.

We need to make a `.dmg`.  @DaytonG, do you have access to a Mac to figure this out?

Typically the disk image includes:

- The `.app` bundle
- A shortcut to `/Applications`
- A pretty picture with an arrow that tells the user to drag the app to the Applications folder

**Comment by DaytonG** [comment]
I do not currently have a mac, no. Chris is working on shipping me one, I think.
